#!/usr/bin/env node
const fs = require("mz/fs");
const util = require("util");
const { findClosures } = require("./src/closure");

async function main() {
    const filename = process.argv[2];
    if (!filename) {
        console.log("Please provide a file name.");
        return;
    }
    const ast = JSON.parse((await fs.readFile(filename)).toString());
    for (let node of ast) {
        const result = findClosures(node, [], []);
        console.log(util.inspect(result, { depth: 10 }));
    }
}

main().catch((err) => console.log(err.stack));
