#!/usr/bin/env node

const fs = require("mz/fs");
const path = require("path");
const { generateCode } = require("./src/generator");

async function main() {
    const filePath = process.argv[2];
    if (!filePath) {
        console.log("Please provide a file name.");
        return;
    }
    const ast = JSON.parse((await fs.readFile(filePath)).toString());
    const codeFilePath = filePath.replace(".ast", ".play");
    const code = (await fs.readFile(codeFilePath)).toString();
    const historyFilePath = filePath.replace(".ast", ".history");
    const profileJsonPath = filePath.replace(".ast", ".profile.json");
    const dir = path.dirname(filePath);
    const outputFilePath = path.join(dir, path.basename(filePath, ".ast") + ".js");
    const jsCode = generateCode(ast, {
        historyFilePath,
        profileJsonPath,
        sourceFilePath: codeFilePath,
        code
    });
    await fs.writeFile(outputFilePath, jsCode);
    console.log(`Wrote ${outputFilePath}.`);
}

main().catch(err => console.log(err.stack));
